name: Apply
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

on:
  push:

jobs:  
  s3-bucket-push:
    name: Github actions job to push to s3
    uses: amitku13/oidc-github/.github/workflows/main.yml@main
    with:
      BUCKET_NAME: vprofileaction13 
      AWS_REGION: "us-east-1"  
      
